-- POPULATING COLLEGE TABLE
INSERT INTO `university_college` (`id`, `title`) VALUES ('1', 'College of Agriculture, Fisheries and Natural Resources');
INSERT INTO `university_college` (`id`, `title`) VALUES ('2', 'College of Arts and Communication');
INSERT INTO `university_college` (`id`, `title`) VALUES ('3', 'College of Business Administration');
INSERT INTO `university_college` (`id`, `title`) VALUES ('4', 'College of Education');
INSERT INTO `university_college` (`id`, `title`) VALUES ('5', 'College of Engineering');
INSERT INTO `university_college` (`id`, `title`) VALUES ('6', 'College of Nursing and Allied Health Sciences');
INSERT INTO `university_college` (`id`, `title`) VALUES ('7', 'College of Science');
INSERT INTO `university_college` (`id`, `title`) VALUES ('8', 'College of Veterinary Medicine');
INSERT INTO `university_college` (`id`, `title`) VALUES ('9', 'College of Law');

-- POPULATING DEGREE PROGRAM TABLE
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS Agriculture in Agricultural Economics', '1');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS Agriculture in Animal Science', '1');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS Agriculture in Crop Science', '1');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS Agriculture in Plant Protection', '1');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS Fisheries in Aquaculture', '1');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Agribusiness', '1');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Agricultural Education', '1');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Agriculture', '1');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Forestry', '1');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('AB in Literature and Language Teaching', '2');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('AB in Political Science', '2');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('AB in Public Administration', '2');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('AB in Sociology', '2');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Community Development', '2');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Criminology', '2');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Development Communication', '2');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('Doctor in Public Administration', '2');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('Doctor of Arts in Language and Literature', '2');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('Doctor of Arts in Language Teaching', '2');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Accountancy', '3');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Business Administration', '3');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Cooperatives', '3');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Entrepreneurship', '3');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Hotel and Restaurant Management', '3');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BSBA in Business Economics', '3');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('Doctor in Business Administration', '3');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('Master in Business Administration', '3');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('Master in Fiscal Administration', '3');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('Master in Public Administration', '3');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('Bachelor of Elementary Education', '4');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('Bachelor of Physical Education', '4');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('Bachelor of Science in Home Economics', '4');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('Bachelor of Science in Industrial Education', '4');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('Bachelor of Secondary Education', '4');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('M.A. in Education', '4');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('M.A. in Language Teaching', '4');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('Ph.D. in Educational Management ', '4');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('Bachelor of Technology in Information Technology', '5');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Agricultural Engineering', '5');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Automotive Technology', '5');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Civil Engineering', '5');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Electrical Engineering', '5');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Mechanical Engineering', '5');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('Master of Agricultural Engineering', '5');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Nursing', '6');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Radiologic Technology', '6');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('M.A. in Nursing', '6');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Biology', '7');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Chemistry', '7');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Environmental Sciences', '7');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Information Technology', '7');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Marine Biology', '7');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Mathematics', '7');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('BS in Meat Technology', '8');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('Doctor of Veterinary Medicine', '8');
INSERT INTO `university_degreeprogram` (`title`, `college_id`) VALUES ('Bachelor of Laws', '9');
