# Generated by Django 4.1.5 on 2023-03-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
    ]
