# Generated by Django 4.1.4 on 2022-12-27 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_profile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
