# Generated by Django 4.1.4 on 2022-12-22 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_alter_profile_user'),
        ('university', '0002_alter_student_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile'),
        ),
    ]
